AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This Template implements an IAM user sally
  and create two s3 buckets 
Parameters:
  sallyPassword:
    Type: String
    NoEcho: true
    Description: sally password

Resources:
  catPics:
    Type: AWS::S3::Bucket
  animalPics:
    Type: AWS::S3::Bucket
  policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allow access to all s3 buckets, except catPics
      ManagedPolicyName: AllowAllS3ExceptCats
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "s3:*"
            Resource: "*"
          - Effect: Deny
            Action: "s3:*"
            Resource: [ !GetAtt catPics.Arn, !Join ['', [!GetAtt catPics.Arn, '/*']]]                   
  sally:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMUserChangePassword
      LoginProfile:
        Password: !Ref sallyPassword
        PasswordResetRequired: true

Outputs:
  catPicsBucketName:
    Description: Bucket name for catPic
    Value: !Ref catPics
  animalPicsBucketName:
    Description: Bucket name for animal pic
    Value: !Ref animalPics
  sallyName:
    Description: Name for sally user
    Value: !Ref sally